/*
 * News Manager
 *
 * UPDAY: frontend task. This service should provide a basic rest API to be used in the upday frontend task.
 *
 * API version: 0.0.1
 * Contact: thun@upday.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	"upday.com/upday-task-fe/internal/lib"
	"upday.com/upday-task-fe/internal/swagger"

	"github.com/rs/cors"
)

func main() {
	_, err := lib.GetDB()
	if err != nil {
		panic(err)
	}

	log.Printf("Server started")
	router := swagger.NewRouter()

	handler := cors.AllowAll().Handler(router)

	log.Fatal(http.ListenAndServe(":8080", handler))
}
