/*
 * News Manager
 *
 * UPDAY: frontend task. This service should provide a basic rest API to be used in the upday frontend task.
 *
 * API version: 0.0.1
 * Contact: thun@upday.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"

	"github.com/gorilla/mux"
	"upday.com/upday-task-fe/internal/control"
)

var boardControl = control.NewBoardControl()

func GetAllCountries(w http.ResponseWriter, r *http.Request) {
	handle(w, r, "GetAllCountries", func() (interface{}, error) {
		return boardControl.List(), nil
	})
}

func GetNewsFromBoard(w http.ResponseWriter, r *http.Request) {
	handle(w, r, "GetAllCountries", func() (interface{}, error) {
		vars := mux.Vars(r)
		boardId := vars["boardId"]

		return boardControl.BoardNews(boardId)
	})
}
