/*
 * News Manager
 *
 * UPDAY: frontend task. This service should provide a basic rest API to be used in the upday frontend task.
 *
 * API version: 0.0.1
 * Contact: thun@upday.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type BoardNews struct {
	Drafts []*News `json:"drafts"`

	Published []*News `json:"published"`

	Archives []*News `json:"archives"`
}
